# Generated by Django 4.0.2 on 2022-02-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=100, null=True, verbose_name='Descripción')),
                ('serial', models.FloatField(max_length=100, null=True, verbose_name='Serial')),
                ('valor', models.FloatField(max_length=100, null=True, verbose_name='Valor')),
                ('fecha', models.DateField(max_length=100, null=True, verbose_name='Fecha')),
                ('estado', models.BooleanField(max_length=100, null=True, verbose_name='Estado')),
            ],
        ),
    ]
