# Generated by Django 4.0.2 on 2022-02-17 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, null=True, verbose_name='Apellidos')),
                ('cargo', models.CharField(choices=[('1', 'Gerente'), ('2', 'Administrador'), ('3', 'Empleado')], max_length=100, null=True, verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('1', 'Tecnología'), ('2', 'Industrial'), ('3', 'Hogar'), ('4', 'Víveres'), ('5', 'Niños'), ('6', 'Mascotas')], max_length=100, null=True, verbose_name='Nombre')),
                ('ubicacion', models.CharField(choices=[('1', 'Norte'), ('2', 'Sur'), ('3', 'Oriente'), ('4', 'Occidente'), ('5', 'NorOriente'), ('6', 'NorOccidete'), ('7', 'SurOriente'), ('8', 'SurOccidente')], max_length=100, null=True, verbose_name='Ubicación')),
                ('descripcion', models.CharField(max_length=100, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.responsable'),
        ),
        migrations.AddField(
            model_name='producto',
            name='seccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.seccion'),
        ),
    ]
